ProTwo/AppTwo/urls.py
from django.contrib import admin
from django.urls import path
from AppTwo import views

app_name = "AppTwo"

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('users/',views.users,name = 'users'),
    path('help/',views.help,name = 'help'),
    path('prfile/',views.userprofile,name = 'userprofile'),
]

ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from AppTwo import views
from django.conf.urls import include

urlpatterns = [
    path('',view = views.index,name = 'index'),
    path('AppTwo/',include('AppTwo.urls')),
    path('admin/', admin.site.urls),
]

ProTwo/AppTwo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class User(models.Model):
#     first_name = models.CharField(max_length = 264)
#     second_name = models.CharField(max_length = 264)
#     email = models.CharField(max_length = 264)
#
#     def __str__(self):
#         return (self.first_name + self.second_name)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete = AttributeError)

    profolio = models.URLField(blank = True)
    picture = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

ProTwo/AppTwo/forms.py
from AppTwo.models import User
from AppTwo.models import UserProfileInfo
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username","email","password")

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = "__all__"

ProTwo/AppTwo/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from AppTwo.models import User
from AppTwo.forms import UserForm
from AppTwo.forms import UserProfileInfoForm
# Create your views here.

def index(request):
    return render(request,"AppTwo/index.html")

def help(request):
    my_dic = {'help_page':'Help Page'}
    return render(request,'AppTwo/help.html',context = my_dic)

def users(request):
    # u = User.objects.order_by("first_name")
    # my_dic = {'user_table':u}
    # return render(request,'AppTwo/user.html',context = my_dic)
    form = UserForm()

    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            form.save()
            return index(request)
        else:
            print("ERROR FROM INVALID")

    return render(request,"AppTwo/user.html",context = {"form":form})

def userprofile(request):
    profileform = UserProfileInfoForm

    if request.method == "POST":
        profileform = UserProfileInfoForm(request.POST)

        if profileform.is_valid():
            profileform.save()
            return index(request)

    return render(request,'AppTwo/profileform.html',context = {"profileform":profileform})

ProTwo/templates/AppTwo/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppTwo:help' %}">Help</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppTwo:users' %}">User</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppTwo:userprofile' %}">User Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inheritted if you extend -->
      {% endblock %}
    </div>

  </body>
</html>

ProTwo/templates/AppTwo/help.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}
    <h1>{{ help_page }}</h1>
    <ul>
      <li><a href="{% url 'index' %}">index page</a></li>
      <li><a href="{% url 'AppTwo:users' %}">User List Page</a></li>
    </ul>
  {% endblock %}

ProTwo/templates/AppTwo/index.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}
    <h1>This is my Index!</h1>
    <ul>
      <li><a href="{% url 'AppTwo:help' %}">help page</a></li>
      <li><a href="{% url 'AppTwo:users' %}">User List Page</a></li>
      <li><a href="{% url 'AppTwo:userprofile' %}">User Profile Page</a></li>
    </ul>
  {% endblock %}

ProTwo/templates/AppTwo/profileform.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}
    <h1>Please fill up the profile form</h1>
    <form method="post">
      {{ profileform.as_p }}
      {% csrf_token %}
      <input type="submit" value="Submit">
    </form>
  {% endblock %}

ProTwo/templates/AppTwo/user.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}
    <form method="post">
    <h1>Registration</h1>
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
    </form>
  {% endblock %}



<!-- present table
{% if user_table %}
  <table>
    <thead>
      <th>First name</th>
      <th>Second Name</th>
      <th>email</th>
    </thead>
    {% for row in user_table %}
      <tr>
        <td>{{ row.first_name }}</td>
        <td>{{ row.second_name }}</td>
        <td>{{ row.email }}</td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>Sorry, there is no user list here</p>
{% endif %} -->